[package]
name = "festive-bot"
version = "0.1.0"
authors = ["Colm Baston <colm@colmbaston.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.6", features = ["blocking"] }
json    = "0.12.4"
