[package]
name        = "festive-bot"
version     = "1.0.6"
authors     = ["Colm Baston"]
edition     = "2021"
description = "A bot to track events occurring on a private Advent of Code leaderboard."
repository  = "https://gitlab.com/colmbaston/festive-bot/"
readme      = "README.md"
license     = "MIT"

[dependencies]
chrono   = "0.4"
num      = "0.4"
json     = "0.12"
ctrlc    = { version = "3.2",  features = ["termination"] }
reqwest  = { version = "0.11", features = ["blocking", "multipart"] }
