[package]
name = "festive-bot"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono   = "0.4"
num      = "0.4"
json     = "0.12"
reqwest  = { version = "0.11", features = ["blocking"]    }
ctrlc    = { version = "3.2",  features = ["termination"] }
