[package]
name        = "festive-bot"
version     = "1.0.7"
authors     = ["Colm Baston"]
edition     = "2021"
description = "A bot to track events occurring on a private Advent of Code leaderboard."
repository  = "https://gitlab.com/colmbaston/festive-bot/"
readme      = "README.md"
license     = "MIT"

[dependencies]
num      = "0.4.0"
json     = "0.12.4"
chrono   = "0.4.23"
ctrlc    = { version = "3.2.3",   features = ["termination"] }
reqwest  = { version = "0.11.13", features = ["blocking", "multipart"] }
